from enum import StrEnum


class NodeType(StrEnum):
    PROCESS = "PROCESS"
    THREAD = "THREAD"
    FILE = "FILE"
    PE = "PE"
    SOCKET = "SOCKET"
    REGISTRY_KEY = "REGISTRY_KEY"
    EXECUTION_RECORD = "EXECUTION_RECORD"
    HYPOTHESIS = "HYPOTHESIS"


class EdgeType(StrEnum):
    SPAWNED = "SPAWNED"
    CONNECTED_TO = "CONNECTED_TO"
    OPENED = "OPENED"
    LOADED = "LOADED"
    PRODUCED_BY = "PRODUCED_BY"
    SUPPORTS = "SUPPORTS"
    CONTRADICTS = "CONTRADICTS"


class HypothesisStatus(StrEnum):
    PROPOSED = "PROPOSED"
    ACTIVE = "ACTIVE"
    VERIFYING = "VERIFYING"
    SUPPORTED = "SUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    REJECTED = "REJECTED"
    INCONCLUSIVE = "INCONCLUSIVE"
